# -*- coding: utf-8 -*-
"""pract-05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2ObBEFCKQl5CdTjDxjPDzd4VjvlKwBG
"""

def knapsack(W, wt, val):
    n = len(wt)
    dp = [[0] * (W + 1) for _ in range(n + 1)]

    for i in range(1, n + 1):
        for w in range(W + 1):
            dp[i][w] = dp[i - 1][w]  # don't take item i-1
            if wt[i - 1] <= w:
                dp[i][w] = max(dp[i][w], val[i - 1] + dp[i - 1][w - wt[i - 1]])  # take it

    return dp[n][W]

wt = [1, 3, 4, 5]
val = [1, 4, 5, 7]
W = 7
print(knapsack(W, wt, val))